### ISSUE TITLE
Issue with mapped units table word document

### ISSUE THREAD

**Issue by marek05** [darwin-eu/CdmOnboarding#1]
There is an issue when generating the word document. The mapped units for measurement and observation table are the same (two identical tables in word document).

The issue is that in generating results document there are two lines referring to measurement units (mappedUnitsMeas). I think it should be mappedUnitsObs:
`my_mapped_section(vocabResults$mappedUnitsMeas, "measurement units", results$smallCellCount) %>%
my_mapped_section(vocabResults$mappedUnitsMeas, "observation units", results$smallCellCount) %>%
`
Location:
https://github.com/darwin-eu/CdmOnboarding/blob/d156e5336b9464d87c4cf16567b194cf22f7b90d/R/GenerateResultsDocument.R#L259

**Comment by MaximMoinat** [comment]
Fixed in v2.2
