### ISSUE TITLE
DrugExposureDiagnostics single quotes (') error

### ISSUE THREAD

**Issue by gian94poli** [darwin-eu/CdmOnboarding#13]
HI!
When running the cdmOnboarding function, an error occurs during the execution of DrugExposureDiagnostics.
Below are the error logs
[log_cdmOnboarding.txt](https://github.com/user-attachments/files/17015642/log_cdmOnboarding.txt)
[errorReportSql.txt](https://github.com/user-attachments/files/17015645/errorReportSql.txt)

We can't figure out where the following query is generated:
**CREATE TABLE 'results1'.'xqvyz_test_table' (speed NUMERIC, dist NUMERIC)**
The problem seems to be the name of our schema (and also the name of the table to be created) which has single quotes (').

R version: 4.1.2
CDMConnector version: 1.5.0
DrugExposureDiagnostics version: 1.0.8
cdmOnboarding version: 3.2.1
posgreSQL version: 10.6

**Comment by MaximMoinat** [comment]
Solved offline
