### ISSUE TITLE
Possible undocumented dependency on DashboardExport

### ISSUE THREAD

**Issue by pasirikala** [darwin-eu/CdmOnboarding#2]
I was running CdmOnboarding::cdmOnboarding trying to follow installation instructions and CodeToRun.R examples.
In the achilles-phase, after getting warning about outdated achilles (unfortunately correct, I have v1.6.7),  I got this error:
**Error in `SqlRender::loadRenderTranslateSql()`:
! Cannot find 'getAchillesAnalyses.sql' in the 'sql' or 'sql/sql_server' folder of the 'DashboardExport' package.**

I looked at the code and it seemed to indeed expect DahsboardExport package, althoug the same sql exists in the CdmOnboarding also.

After installing DahsboardExport, this error disappeared.

EDIT: I just realized, running DashboardExport is also required for onboarding process, so this issue is irrelevant - DashboardExport needs to be installed anyway...

**Comment by MaximMoinat** [comment]
Thanks for reporting, we will fix this in an upcoming release.
