### ISSUE TITLE
Drug exposure Checks seem to be incompatible with some RDBM systems (Synapse Analytics dedicated instance)

### ISSUE THREAD

**Issue by pasirikala** [darwin-eu/CdmOnboarding#4]
I am trying to run CdmOnboarding::cdmOnboarding against a Synapse Analytics dedicated instance database.

During the DrugExposureDiagnostics I get this error:
**Execution of DrugExposureDiagnostics failed: Error in rJava::.jcall(resultSet, "Z", "next"): com.microsoft.sqlserver.jdbc.SQLServerException: USE statement is not supported to switch between databases. Use a new connection to connect to a different Database.**

This seems to be caused by 
`cdm <- CDMConnector::cdm_from_con(connection, cdm_schema = cdmDatabaseSchema)`
at the R/DedChecks.R.

If I am correct, this database, although it resembles sqlserver in many ways, does not support USE statement.
We need to find a way to execute checks without requiring USE statement.

**Comment by MaximMoinat** [comment]
Synapse Analytics is currently not supported by CdmConnector, which is needed for the DrugExposureDiagnostics results
