### ISSUE TITLE
Missing vocabulary schema option

### ISSUE THREAD

**Issue by Gaelle-R** [darwin-eu/CdmOnboarding#6]
Hi !

In the "CDMOnboarding" package, there are two functions that don't allow to specify a vocabulary schema : 
- For https://github.com/darwin-eu/CdmOnboarding/blob/main/R/CdmOnboarding.R : the function dataTablesResults the parameter vocabDatabaseSchema is missing (see : PR #5 )
- For https://github.com/darwin-eu/CdmOnboarding/blob/main/R/DedChecks.R (lines 40-41) : the function cdm_from_conn from the CDMConnector package does not allow to specify a vocabulary schema, when it is not the same as the CDM one. 

Thanks for your help !

**Comment by MaximMoinat** [comment]
Thanks for raising this issue and making a PR.

We are going to remove support for a separate vocabulary schema. Most DARWIN analytics (and e.g. OHDSI Atlas) does not support this.

Please consider moving your vocabulary tables to the cdm schema. A workaround is to create views in the cdm schema referring to the tables in the vocabulary schema.
