### ISSUE TITLE
Error while generate results document

### ISSUE THREAD

**Issue by donni29** [darwin-eu/CdmOnboarding#8]
After the cdmOnboarding execution is completed, the results document is not generated. 
The following error is encountered: 
_**Colud not generate results document: Error in UseMethod("mutate"): no applicable method for 'mutate' applied to an object of class "NULL".**_
The code executed is the default code recommended within this repository.
The error is found in both version 2.2 and version 2.1.

**Comment by MaximMoinat** [comment]
Thanks for reporting. Is there any other error thrown before this one? It seems one dataframe is empty, which might be caused by one of the queries failing.

**Comment by donni29** [comment]
The only error we were able to detect while running the package is the following: 
_2023-10-25 08:02:51 [Main thread] ERROR CdmOnboarding 3 Could not connect to the WebAPI on 'example: 'http://localhost:8080/WebAPI/info' --> with WebAPI running': Error in curl::curl_fetch_memory(url, handle = handle): URL using bad/illegal format or missing URL ._
All other queries are executed successfully.
We use webapi via Docker container.
The same error was thrown by running the CdmInspection package, but in that case the document was still generated.

**Comment by MaximMoinat** [comment]
If the .rds file has been created, it would be best to debug from there. Please contact me directly (m.moinat [at] darwin-eu.org).
