### ISSUE TITLE
Should DashboardExport be a dependency?

### ISSUE THREAD

**Issue by hezekiah2022** [darwin-eu/CdmOnboarding#9]
Hi, when running this package we had an issue because I did not have DashboardExport installed on my machine (and resolved when I installed DashboardExport)

```
Error in `SqlRender::loadRenderTranslateSql()`:
! Cannot find 'getAchillesAnalyses.sql' in the 'sql' or 'sql/sql_server' folder of the 'DashboardExport' package.
```

**Comment by MaximMoinat** [comment]
It indeed should not and we have fixed this in the upcoming release.
